#!/usr/bin/env zsh

alias kaf="kubectl apply --recursive -f"
alias kccj="kubectl create cronjobs"
alias kccjn="kubectl create cronjobs --namespace"
alias kccm="kubectl create configmaps"
alias kccmn="kubectl create configmaps --namespace"
alias kccr="kubectl create clusterroles"
alias kccrb="kubectl create clusterrolebindings"
alias kccrd="kubectl create customresourcedefinitions"
alias kccsr="kubectl create certificatesigningrequests"
alias kcdep="kubectl create deployments"
alias kcdepn="kubectl create deployments --namespace"
alias kcds="kubectl create daemonsets"
alias kcdsn="kubectl create daemonsets --namespace"
alias kcep="kubectl create endpoints"
alias kcepn="kubectl create endpoints --namespace"
alias kces="kubectl create endpointslices"
alias kcesn="kubectl create endpointslices --namespace"
alias kcev="kubectl create events"
alias kcevn="kubectl create events --namespace"
alias kcfs="kubectl create flowschemas"
alias kchpa="kubectl create horizontalpodautoscalers"
alias kchpan="kubectl create horizontalpodautoscalers --namespace"
alias kcing="kubectl create ingresses"
alias kcingcls="kubectl create ingressclasses"
alias kcingn="kubectl create ingresses --namespace"
alias kcjob="kubectl create jobs"
alias kcjobn="kubectl create jobs --namespace"
alias kclease="kubectl create leases"
alias kcleasen="kubectl create leases --namespace"
alias kclimits="kubectl create limitranges"
alias kclimitsn="kubectl create limitranges --namespace"
alias kcnetpol="kubectl create networkpolicies"
alias kcnetpoln="kubectl create networkpolicies --namespace"
alias kcns="kubectl create namespaces"
alias kcpc="kubectl create priorityclasses"
alias kcpdb="kubectl create poddisruptionbudgets"
alias kcpdbn="kubectl create poddisruptionbudgets --namespace"
alias kcplc="kubectl create prioritylevelconfigurations"
alias kcpo="kubectl create pods"
alias kcpodt="kubectl create podtemplates"
alias kcpodtn="kubectl create podtemplates --namespace"
alias kcpon="kubectl create pods --namespace"
alias kcpv="kubectl create persistentvolumes"
alias kcpvc="kubectl create persistentvolumeclaims"
alias kcpvcn="kubectl create persistentvolumeclaims --namespace"
alias kcqu="kubectl create resourcequotas"
alias kcqun="kubectl create resourcequotas --namespace"
alias kcrb="kubectl create rolebindings"
alias kcrbn="kubectl create rolebindings --namespace"
alias kcrc="kubectl create replicationcontrollers"
alias kcrcn="kubectl create replicationcontrollers --namespace"
alias kcro="kubectl create roles"
alias kcron="kubectl create roles --namespace"
alias kcrs="kubectl create replicasets"
alias kcrsn="kubectl create replicasets --namespace"
alias kcrtcls="kubectl create runtimeclasses"
alias kcsa="kubectl create serviceaccounts"
alias kcsan="kubectl create serviceaccounts --namespace"
alias kcsc="kubectl create storageclasses"
alias kcsec="kubectl create secrets"
alias kcsecn="kubectl create secrets --namespace"
alias kcsts="kubectl create statefulsets"
alias kcstsn="kubectl create statefulsets --namespace"
alias kcsvc="kubectl create services"
alias kcsvcn="kubectl create services --namespace"
alias kctx="kubectx"
alias kcva="kubectl create volumeattachments"
alias kd="kubectl describe"
alias kdapis="kubectl describe apiservices"
alias kdcj="kubectl describe cronjobs"
alias kdcjn="kubectl describe cronjobs --namespace"
alias kdcm="kubectl describe configmaps"
alias kdcmn="kubectl describe configmaps --namespace"
alias kdcr="kubectl describe clusterroles"
alias kdcrb="kubectl describe clusterrolebindings"
alias kdcrd="kubectl describe customresourcedefinitions"
alias kdcsr="kubectl describe certificatesigningrequests"
alias kddep="kubectl describe deployments"
alias kddepn="kubectl describe deployments --namespace"
alias kdds="kubectl describe daemonsets"
alias kddsn="kubectl describe daemonsets --namespace"
alias kdep="kubectl describe endpoints"
alias kdepn="kubectl describe endpoints --namespace"
alias kdes="kubectl describe endpointslices"
alias kdesn="kubectl describe endpointslices --namespace"
alias kdev="kubectl describe events"
alias kdevn="kubectl describe events --namespace"
alias kdfs="kubectl describe flowschemas"
alias kdhpa="kubectl describe horizontalpodautoscalers"
alias kdhpan="kubectl describe horizontalpodautoscalers --namespace"
alias kding="kubectl describe ingresses"
alias kdingcls="kubectl describe ingressclasses"
alias kdingn="kubectl describe ingresses --namespace"
alias kdjob="kubectl describe jobs"
alias kdjobn="kubectl describe jobs --namespace"
alias kdlease="kubectl describe leases"
alias kdleasen="kubectl describe leases --namespace"
alias kdlimits="kubectl describe limitranges"
alias kdlimitsn="kubectl describe limitranges --namespace"
alias kdnetpol="kubectl describe networkpolicies"
alias kdnetpoln="kubectl describe networkpolicies --namespace"
alias kdno="kubectl describe nodes"
alias kdns="kubectl describe namespaces"
alias kdpc="kubectl describe priorityclasses"
alias kdpdb="kubectl describe poddisruptionbudgets"
alias kdpdbn="kubectl describe poddisruptionbudgets --namespace"
alias kdplc="kubectl describe prioritylevelconfigurations"
alias kdpo="kubectl describe pods"
alias kdpodt="kubectl describe podtemplates"
alias kdpodtn="kubectl describe podtemplates --namespace"
alias kdpon="kubectl describe pods --namespace"
alias kdpv="kubectl describe persistentvolumes"
alias kdpvc="kubectl describe persistentvolumeclaims"
alias kdpvcn="kubectl describe persistentvolumeclaims --namespace"
alias kdqu="kubectl describe resourcequotas"
alias kdqun="kubectl describe resourcequotas --namespace"
alias kdrb="kubectl describe rolebindings"
alias kdrbn="kubectl describe rolebindings --namespace"
alias kdrc="kubectl describe replicationcontrollers"
alias kdrcn="kubectl describe replicationcontrollers --namespace"
alias kdro="kubectl describe roles"
alias kdron="kubectl describe roles --namespace"
alias kdrs="kubectl describe replicasets"
alias kdrsn="kubectl describe replicasets --namespace"
alias kdrtcls="kubectl describe runtimeclasses"
alias kdsa="kubectl describe serviceaccounts"
alias kdsan="kubectl describe serviceaccounts --namespace"
alias kdsc="kubectl describe storageclasses"
alias kdsec="kubectl describe secrets"
alias kdsecn="kubectl describe secrets --namespace"
alias kdsts="kubectl describe statefulsets"
alias kdstsn="kubectl describe statefulsets --namespace"
alias kdsvc="kubectl describe services"
alias kdsvcn="kubectl describe services --namespace"
alias kdva="kubectl describe volumeattachments"
alias kex="kubectl exec -it"
alias kg="kubectl get"
alias kgapis="kubectl get apiservices"
alias kgapisl="kubectl get apiservices --selector"
alias kgapisoj="kubectl get apiservices --output=json"
alias kgapisow="kubectl get apiservices --output=wide"
alias kgapisoy="kubectl get apiservices --output=yaml"
alias kgapissl="kubectl get apiservices --show-labels"
alias kgapisw="kubectl get apiservices --watch"
alias kgcj="kubectl get cronjobs"
alias kgcjall="kubectl get cronjobs --all-namespaces"
alias kgcjl="kubectl get cronjobs --selector"
alias kgcjn="kubectl get cronjobs --namespace"
alias kgcjoj="kubectl get cronjobs --output=json"
alias kgcjow="kubectl get cronjobs --output=wide"
alias kgcjoy="kubectl get cronjobs --output=yaml"
alias kgcjsl="kubectl get cronjobs --show-labels"
alias kgcjw="kubectl get cronjobs --watch"
alias kgcm="kubectl get configmaps"
alias kgcmall="kubectl get configmaps --all-namespaces"
alias kgcml="kubectl get configmaps --selector"
alias kgcmn="kubectl get configmaps --namespace"
alias kgcmoj="kubectl get configmaps --output=json"
alias kgcmow="kubectl get configmaps --output=wide"
alias kgcmoy="kubectl get configmaps --output=yaml"
alias kgcmsl="kubectl get configmaps --show-labels"
alias kgcmw="kubectl get configmaps --watch"
alias kgcr="kubectl get clusterroles"
alias kgcrb="kubectl get clusterrolebindings"
alias kgcrboj="kubectl get clusterrolebindings --output=json"
alias kgcrbow="kubectl get clusterrolebindings --output=wide"
alias kgcrboy="kubectl get clusterrolebindings --output=yaml"
alias kgcrbsl="kubectl get clusterrolebindings --show-labels"
alias kgcrd="kubectl get customresourcedefinitions"
alias kgcrdoj="kubectl get customresourcedefinitions --output=json"
alias kgcrdow="kubectl get customresourcedefinitions --output=wide"
alias kgcrdoy="kubectl get customresourcedefinitions --output=yaml"
alias kgcrdsl="kubectl get customresourcedefinitions --show-labels"
alias kgcrl="kubectl get clusterroles --selector"
alias kgcrlb="kubectl get clusterrolebindings --selector"
alias kgcrld="kubectl get customresourcedefinitions --selector"
alias kgcroj="kubectl get clusterroles --output=json"
alias kgcrow="kubectl get clusterroles --output=wide"
alias kgcroy="kubectl get clusterroles --output=yaml"
alias kgcrsl="kubectl get clusterroles --show-labels"
alias kgcrw="kubectl get clusterroles --watch"
alias kgcrwb="kubectl get clusterrolebindings --watch"
alias kgcrwd="kubectl get customresourcedefinitions --watch"
alias kgcsr="kubectl get certificatesigningrequests"
alias kgcsrl="kubectl get certificatesigningrequests --selector"
alias kgcsroj="kubectl get certificatesigningrequests --output=json"
alias kgcsrow="kubectl get certificatesigningrequests --output=wide"
alias kgcsroy="kubectl get certificatesigningrequests --output=yaml"
alias kgcsrsl="kubectl get certificatesigningrequests --show-labels"
alias kgcsrw="kubectl get certificatesigningrequests --watch"
alias kgdep="kubectl get deployments"
alias kgdepall="kubectl get deployments --all-namespaces"
alias kgdepl="kubectl get deployments --selector"
alias kgdepn="kubectl get deployments --namespace"
alias kgdepoj="kubectl get deployments --output=json"
alias kgdepow="kubectl get deployments --output=wide"
alias kgdepoy="kubectl get deployments --output=yaml"
alias kgdepsl="kubectl get deployments --show-labels"
alias kgdepw="kubectl get deployments --watch"
alias kgds="kubectl get daemonsets"
alias kgdsall="kubectl get daemonsets --all-namespaces"
alias kgdsl="kubectl get daemonsets --selector"
alias kgdsn="kubectl get daemonsets --namespace"
alias kgdsoj="kubectl get daemonsets --output=json"
alias kgdsow="kubectl get daemonsets --output=wide"
alias kgdsoy="kubectl get daemonsets --output=yaml"
alias kgdssl="kubectl get daemonsets --show-labels"
alias kgdsw="kubectl get daemonsets --watch"
alias kgep="kubectl get endpoints"
alias kgepall="kubectl get endpoints --all-namespaces"
alias kgepl="kubectl get endpoints --selector"
alias kgepn="kubectl get endpoints --namespace"
alias kgepoj="kubectl get endpoints --output=json"
alias kgepow="kubectl get endpoints --output=wide"
alias kgepoy="kubectl get endpoints --output=yaml"
alias kgepsl="kubectl get endpoints --show-labels"
alias kgepw="kubectl get endpoints --watch"
alias kges="kubectl get endpointslices"
alias kgesall="kubectl get endpointslices --all-namespaces"
alias kgesl="kubectl get endpointslices --selector"
alias kgesn="kubectl get endpointslices --namespace"
alias kgesoj="kubectl get endpointslices --output=json"
alias kgesow="kubectl get endpointslices --output=wide"
alias kgesoy="kubectl get endpointslices --output=yaml"
alias kgessl="kubectl get endpointslices --show-labels"
alias kgesw="kubectl get endpointslices --watch"
alias kgev="kubectl get events"
alias kgevall="kubectl get events --all-namespaces"
alias kgevl="kubectl get events --selector"
alias kgevn="kubectl get events --namespace"
alias kgevoj="kubectl get events --output=json"
alias kgevow="kubectl get events --output=wide"
alias kgevoy="kubectl get events --output=yaml"
alias kgevsl="kubectl get events --show-labels"
alias kgevw="kubectl get events --watch"
alias kgfs="kubectl get flowschemas"
alias kgfsl="kubectl get flowschemas --selector"
alias kgfsoj="kubectl get flowschemas --output=json"
alias kgfsow="kubectl get flowschemas --output=wide"
alias kgfsoy="kubectl get flowschemas --output=yaml"
alias kgfssl="kubectl get flowschemas --show-labels"
alias kgfsw="kubectl get flowschemas --watch"
alias kghpa="kubectl get horizontalpodautoscalers"
alias kghpaall="kubectl get horizontalpodautoscalers --all-namespaces"
alias kghpal="kubectl get horizontalpodautoscalers --selector"
alias kghpan="kubectl get horizontalpodautoscalers --namespace"
alias kghpaoj="kubectl get horizontalpodautoscalers --output=json"
alias kghpaow="kubectl get horizontalpodautoscalers --output=wide"
alias kghpaoy="kubectl get horizontalpodautoscalers --output=yaml"
alias kghpasl="kubectl get horizontalpodautoscalers --show-labels"
alias kghpaw="kubectl get horizontalpodautoscalers --watch"
alias kging="kubectl get ingresses"
alias kgingall="kubectl get ingresses --all-namespaces"
alias kgingcls="kubectl get ingressclasses"
alias kgingclsl="kubectl get ingressclasses --selector"
alias kgingclsls="kubectl get ingressclasses --show-labels"
alias kgingclsoj="kubectl get ingressclasses --output=json"
alias kgingclsow="kubectl get ingressclasses --output=wide"
alias kgingclsoy="kubectl get ingressclasses --output=yaml"
alias kgingclsw="kubectl get ingressclasses --watch"
alias kgingl="kubectl get ingresses --selector"
alias kgingn="kubectl get ingresses --namespace"
alias kgingoj="kubectl get ingresses --output=json"
alias kgingow="kubectl get ingresses --output=wide"
alias kgingoy="kubectl get ingresses --output=yaml"
alias kgingsl="kubectl get ingresses --show-labels"
alias kgingw="kubectl get ingresses --watch"
alias kgjob="kubectl get jobs"
alias kgjoball="kubectl get jobs --all-namespaces"
alias kgjobl="kubectl get jobs --selector"
alias kgjobn="kubectl get jobs --namespace"
alias kgjoboj="kubectl get jobs --output=json"
alias kgjobow="kubectl get jobs --output=wide"
alias kgjoboy="kubectl get jobs --output=yaml"
alias kgjobsl="kubectl get jobs --show-labels"
alias kgjobw="kubectl get jobs --watch"
alias kglease="kubectl get leases"
alias kgleaseall="kubectl get leases --all-namespaces"
alias kgleasel="kubectl get leases --selector"
alias kgleasen="kubectl get leases --namespace"
alias kgleaseoj="kubectl get leases --output=json"
alias kgleaseow="kubectl get leases --output=wide"
alias kgleaseoy="kubectl get leases --output=yaml"
alias kgleasesl="kubectl get leases --show-labels"
alias kgleasew="kubectl get leases --watch"
alias kglimits="kubectl get limitranges"
alias kglimitsall="kubectl get limitranges --all-namespaces"
alias kglimitsl="kubectl get limitranges --selector"
alias kglimitsn="kubectl get limitranges --namespace"
alias kglimitsoj="kubectl get limitranges --output=json"
alias kglimitsow="kubectl get limitranges --output=wide"
alias kglimitsoy="kubectl get limitranges --output=yaml"
alias kglimitssl="kubectl get limitranges --show-labels"
alias kglimitsw="kubectl get limitranges --watch"
alias kgneltpol="kubectl get networkpolicies --selector"
alias kgnetpol="kubectl get networkpolicies"
alias kgnetpolall="kubectl get networkpolicies --all-namespaces"
alias kgnetpoln="kubectl get networkpolicies --namespace"
alias kgnetpoloj="kubectl get networkpolicies --output=json"
alias kgnetpolow="kubectl get networkpolicies --output=wide"
alias kgnetpoloy="kubectl get networkpolicies --output=yaml"
alias kgnetpolsl="kubectl get networkpolicies --show-labels"
alias kgnetpolw="kubectl get networkpolicies --watch"
alias kgno="kubectl get nodes"
alias kgnol="kubectl get nodes --selector"
alias kgnooj="kubectl get nodes --output=json"
alias kgnoow="kubectl get nodes --output=wide"
alias kgnooy="kubectl get nodes --output=yaml"
alias kgnosl="kubectl get nodes --show-labels"
alias kgnow="kubectl get nodes --watch"
alias kgns="kubectl get namespaces"
alias kgnsl="kubectl get namespaces --selector"
alias kgnsoj="kubectl get namespaces --output=json"
alias kgnsow="kubectl get namespaces --output=wide"
alias kgnsoy="kubectl get namespaces --output=yaml"
alias kgnssl="kubectl get namespaces --show-labels"
alias kgnsw="kubectl get namespaces --watch"
alias kgpc="kubectl get priorityclasses"
alias kgpcl="kubectl get priorityclasses --selector"
alias kgpcoj="kubectl get priorityclasses --output=json"
alias kgpcow="kubectl get priorityclasses --output=wide"
alias kgpcoy="kubectl get priorityclasses --output=yaml"
alias kgpcsl="kubectl get priorityclasses --show-labels"
alias kgpcw="kubectl get priorityclasses --watch"
alias kgpdb="kubectl get poddisruptionbudgets"
alias kgpdball="kubectl get poddisruptionbudgets --all-namespaces"
alias kgpdbl="kubectl get poddisruptionbudgets --selector"
alias kgpdbn="kubectl get poddisruptionbudgets --namespace"
alias kgpdboj="kubectl get poddisruptionbudgets --output=json"
alias kgpdbow="kubectl get poddisruptionbudgets --output=wide"
alias kgpdboy="kubectl get poddisruptionbudgets --output=yaml"
alias kgpdbsl="kubectl get poddisruptionbudgets --show-labels"
alias kgpdbw="kubectl get poddisruptionbudgets --watch"
alias kgplc="kubectl get prioritylevelconfigurations"
alias kgplcl="kubectl get prioritylevelconfigurations --selector"
alias kgplcoj="kubectl get prioritylevelconfigurations --output=json"
alias kgplcow="kubectl get prioritylevelconfigurations --output=wide"
alias kgplcoy="kubectl get prioritylevelconfigurations --output=yaml"
alias kgplcsl="kubectl get prioritylevelconfigurations --show-labels"
alias kgplcw="kubectl get prioritylevelconfigurations --watch"
alias kgpo="kubectl get pods"
alias kgpoall="kubectl get pods --all-namespaces"
alias kgpodt="kubectl get podtemplates"
alias kgpodtall="kubectl get podtemplates --all-namespaces"
alias kgpodtl="kubectl get podtemplates --selector"
alias kgpodtn="kubectl get podtemplates --namespace"
alias kgpodtoj="kubectl get podtemplates --output=json"
alias kgpodtow="kubectl get podtemplates --output=wide"
alias kgpodtoy="kubectl get podtemplates --output=yaml"
alias kgpodtsl="kubectl get podtemplates --show-labels"
alias kgpodtw="kubectl get podtemplates --watch"
alias kgpol="kubectl get pods --selector"
alias kgpon="kubectl get pods --namespace"
alias kgpooj="kubectl get pods --output=json"
alias kgpoow="kubectl get pods --output=wide"
alias kgpooy="kubectl get pods --output=yaml"
alias kgposl="kubectl get pods --show-labels"
alias kgpow="kubectl get pods --watch"
alias kgpv="kubectl get persistentvolumes"
alias kgpvc="kubectl get persistentvolumeclaims"
alias kgpvcall="kubectl get persistentvolumeclaims --all-namespaces"
alias kgpvcl="kubectl get persistentvolumeclaims --selector"
alias kgpvcn="kubectl get persistentvolumeclaims --namespace"
alias kgpvcoj="kubectl get persistentvolumeclaims --output=json"
alias kgpvcow="kubectl get persistentvolumeclaims --output=wide"
alias kgpvcoy="kubectl get persistentvolumeclaims --output=yaml"
alias kgpvcsl="kubectl get persistentvolumeclaims --show-labels"
alias kgpvcw="kubectl get persistentvolumeclaims --watch"
alias kgpvl="kubectl get persistentvolumes --selector"
alias kgpvoj="kubectl get persistentvolumes --output=json"
alias kgpvow="kubectl get persistentvolumes --output=wide"
alias kgpvoy="kubectl get persistentvolumes --output=yaml"
alias kgpvsl="kubectl get persistentvolumes --show-labels"
alias kgpvw="kubectl get persistentvolumes --watch"
alias kgqu="kubectl get resourcequotas"
alias kgquall="kubectl get resourcequotas --all-namespaces"
alias kgqul="kubectl get resourcequotas --selector"
alias kgqun="kubectl get resourcequotas --namespace"
alias kgquoj="kubectl get resourcequotas --output=json"
alias kgquow="kubectl get resourcequotas --output=wide"
alias kgquoy="kubectl get resourcequotas --output=yaml"
alias kgqusl="kubectl get resourcequotas --show-labels"
alias kgquw="kubectl get resourcequotas --watch"
alias kgrb="kubectl get rolebindings"
alias kgrball="kubectl get rolebindings --all-namespaces"
alias kgrbl="kubectl get rolebindings --selector"
alias kgrbn="kubectl get rolebindings --namespace"
alias kgrboj="kubectl get rolebindings --output=json"
alias kgrbow="kubectl get rolebindings --output=wide"
alias kgrboy="kubectl get rolebindings --output=yaml"
alias kgrbsl="kubectl get rolebindings --show-labels"
alias kgrbw="kubectl get rolebindings --watch"
alias kgrc="kubectl get replicationcontrollers"
alias kgrcall="kubectl get replicationcontrollers --all-namespaces"
alias kgrcl="kubectl get replicationcontrollers --selector"
alias kgrcn="kubectl get replicationcontrollers --namespace"
alias kgrcoj="kubectl get replicationcontrollers --output=json"
alias kgrcow="kubectl get replicationcontrollers --output=wide"
alias kgrcoy="kubectl get replicationcontrollers --output=yaml"
alias kgrcsl="kubectl get replicationcontrollers --show-labels"
alias kgrcw="kubectl get replicationcontrollers --watch"
alias kgro="kubectl get roles"
alias kgroall="kubectl get roles --all-namespaces"
alias kgrol="kubectl get roles --selector"
alias kgron="kubectl get roles --namespace"
alias kgrooj="kubectl get roles --output=json"
alias kgroow="kubectl get roles --output=wide"
alias kgrooy="kubectl get roles --output=yaml"
alias kgrosl="kubectl get roles --show-labels"
alias kgrow="kubectl get roles --watch"
alias kgrs="kubectl get replicasets"
alias kgrsall="kubectl get replicasets --all-namespaces"
alias kgrsl="kubectl get replicasets --selector"
alias kgrsn="kubectl get replicasets --namespace"
alias kgrsoj="kubectl get replicasets --output=json"
alias kgrsow="kubectl get replicasets --output=wide"
alias kgrsoy="kubectl get replicasets --output=yaml"
alias kgrssl="kubectl get replicasets --show-labels"
alias kgrsw="kubectl get replicasets --watch"
alias kgrtcls="kubectl get runtimeclasses"
alias kgrtclsoj="kubectl get runtimeclasses --output=json"
alias kgrtclsow="kubectl get runtimeclasses --output=wide"
alias kgrtclsoy="kubectl get runtimeclasses --output=yaml"
alias kgrtclssl="kubectl get runtimeclasses --show-labels"
alias kgrtclsw="kubectl get runtimeclasses --watch"
alias kgrtlcls="kubectl get runtimeclasses --selector"
alias kgsa="kubectl get serviceaccounts"
alias kgsaall="kubectl get serviceaccounts --all-namespaces"
alias kgsal="kubectl get serviceaccounts --selector"
alias kgsan="kubectl get serviceaccounts --namespace"
alias kgsaoj="kubectl get serviceaccounts --output=json"
alias kgsaow="kubectl get serviceaccounts --output=wide"
alias kgsaoy="kubectl get serviceaccounts --output=yaml"
alias kgsasl="kubectl get serviceaccounts --show-labels"
alias kgsaw="kubectl get serviceaccounts --watch"
alias kgsc="kubectl get storageclasses"
alias kgscl="kubectl get storageclasses --selector"
alias kgscoj="kubectl get storageclasses --output=json"
alias kgscow="kubectl get storageclasses --output=wide"
alias kgscoy="kubectl get storageclasses --output=yaml"
alias kgscsl="kubectl get storageclasses --show-labels"
alias kgscw="kubectl get storageclasses --watch"
alias kgsec="kubectl get secrets"
alias kgsecall="kubectl get secrets --all-namespaces"
alias kgsecl="kubectl get secrets --selector"
alias kgsecn="kubectl get secrets --namespace"
alias kgsecoj="kubectl get secrets --output=json"
alias kgsecow="kubectl get secrets --output=wide"
alias kgsecoy="kubectl get secrets --output=yaml"
alias kgsecsl="kubectl get secrets --show-labels"
alias kgsecw="kubectl get secrets --watch"
alias kgsts="kubectl get statefulsets"
alias kgstsall="kubectl get statefulsets --all-namespaces"
alias kgstsl="kubectl get statefulsets --selector"
alias kgstsn="kubectl get statefulsets --namespace"
alias kgstsoj="kubectl get statefulsets --output=json"
alias kgstsow="kubectl get statefulsets --output=wide"
alias kgstsoy="kubectl get statefulsets --output=yaml"
alias kgstssl="kubectl get statefulsets --show-labels"
alias kgstsw="kubectl get statefulsets --watch"
alias kgsvc="kubectl get services"
alias kgsvcall="kubectl get services --all-namespaces"
alias kgsvcl="kubectl get services --selector"
alias kgsvcn="kubectl get services --namespace"
alias kgsvcoj="kubectl get services --output=json"
alias kgsvcow="kubectl get services --output=wide"
alias kgsvcoy="kubectl get services --output=yaml"
alias kgsvcsl="kubectl get services --show-labels"
alias kgsvcw="kubectl get services --watch"
alias kgva="kubectl get volumeattachments"
alias kgval="kubectl get volumeattachments --selector"
alias kgvaoj="kubectl get volumeattachments --output=json"
alias kgvaow="kubectl get volumeattachments --output=wide"
alias kgvaoy="kubectl get volumeattachments --output=yaml"
alias kgvasl="kubectl get volumeattachments --show-labels"
alias kgvaw="kubectl get volumeattachments --watch"
alias klo="kubectl logs -f"
alias kns="kubens"
alias krm="kubectl delete"
alias krmapis="kubectl delete apiservices"
alias krmcj="kubectl delete cronjobs"
alias krmcjall="kubectl delete cronjobs --all"
alias krmcjn="kubectl delete cronjobs --namespace"
alias krmcm="kubectl delete configmaps"
alias krmcmn="kubectl delete configmaps --namespace"
alias krmcr="kubectl delete clusterroles"
alias krmcrb="kubectl delete clusterrolebindings"
alias krmcrd="kubectl delete customresourcedefinitions"
alias krmcsr="kubectl delete certificatesigningrequests"
alias krmdep="kubectl delete deployments"
alias krmdepn="kubectl delete deployments --namespace"
alias krmds="kubectl delete daemonsets"
alias krmdsn="kubectl delete daemonsets --namespace"
alias krmep="kubectl delete endpoints"
alias krmepn="kubectl delete endpoints --namespace"
alias krmes="kubectl delete endpointslices"
alias krmesn="kubectl delete endpointslices --namespace"
alias krmev="kubectl delete events"
alias krmevn="kubectl delete events --namespace"
alias krmfs="kubectl delete flowschemas"
alias krmhpa="kubectl delete horizontalpodautoscalers"
alias krmhpan="kubectl delete horizontalpodautoscalers --namespace"
alias krming="kubectl delete ingresses"
alias krmingcls="kubectl delete ingressclasses"
alias krmingn="kubectl delete ingresses --namespace"
alias krmjob="kubectl delete jobs"
alias krmjoball="kubectl delete jobs --all"
alias krmjobn="kubectl delete jobs --namespace"
alias krmlease="kubectl delete leases"
alias krmleasen="kubectl delete leases --namespace"
alias krmlimits="kubectl delete limitranges"
alias krmlimitsn="kubectl delete limitranges --namespace"
alias krmnetpol="kubectl delete networkpolicies"
alias krmnetpoln="kubectl delete networkpolicies --namespace"
alias krmns="kubectl delete namespaces"
alias krmpc="kubectl delete priorityclasses"
alias krmpdb="kubectl delete poddisruptionbudgets"
alias krmpdbn="kubectl delete poddisruptionbudgets --namespace"
alias krmplc="kubectl delete prioritylevelconfigurations"
alias krmpo="kubectl delete pods"
alias krmpodt="kubectl delete podtemplates"
alias krmpodtn="kubectl delete podtemplates --namespace"
alias krmpon="kubectl delete pods --namespace"
alias krmpv="kubectl delete persistentvolumes"
alias krmpvc="kubectl delete persistentvolumeclaims"
alias krmpvcn="kubectl delete persistentvolumeclaims --namespace"
alias krmqu="kubectl delete resourcequotas"
alias krmqun="kubectl delete resourcequotas --namespace"
alias krmrb="kubectl delete rolebindings"
alias krmrbn="kubectl delete rolebindings --namespace"
alias krmrc="kubectl delete replicationcontrollers"
alias krmrcn="kubectl delete replicationcontrollers --namespace"
alias krmro="kubectl delete roles"
alias krmron="kubectl delete roles --namespace"
alias krmrs="kubectl delete replicasets"
alias krmrsn="kubectl delete replicasets --namespace"
alias krmrtcls="kubectl delete runtimeclasses"
alias krmsa="kubectl delete serviceaccounts"
alias krmsan="kubectl delete serviceaccounts --namespace"
alias krmsc="kubectl delete storageclasses"
alias krmsec="kubectl delete secrets"
alias krmsecn="kubectl delete secrets --namespace"
alias krmsts="kubectl delete statefulsets"
alias krmstsn="kubectl delete statefulsets --namespace"
alias krmsvc="kubectl delete services"
alias krmsvcn="kubectl delete services --namespace"
alias krmva="kubectl delete volumeattachments"
alias krmf="kubectl delete --recursive -f"
